server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/board-db # DB ??
    username: root # DB ??
    password: password # DB ????
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    # Kafka 서버 주소
    bootstrap-servers: localhost:9092
    # 게시글 서비스에서는 메시지를 produce 하기만 함
    producer:
      # 메시지의 key 직렬화 방식 : 자바 객체를 문자열(String)로 변환해서 Kafka에 전송
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      # 메시지의 value 직렬화 방식 : 자바 객체를 문자열(String)로 변환해서 Kafka에 전송
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: board-service   # ← 이거 추가!
      auto-offset-reset: earliest  # (추천)
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

client:
  user-service:
    url: http://localhost:8080
  point-service:
    url: http://localhost:8082
