server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/board-db # DB ??
    username: root # DB ??
    password: password # DB ????
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

client:
  user-service:
    url: http://localhost:8080